const wineries = [
  {
    name: 'Kastania Vineyards',
    img: {
      url: '/static/images/wineries/kastania.jpg',
      altText: 'Kstania Vineyards',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Cabernet Franc', 'Cabernet Savingnon'],
    website: 'http://www.kastaniavineyards.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Black Kite Cellars',
    img: {
      url: '/static/images/wineries/black_kite.jpg',
      altText: 'Kite Cellars',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'http://blackkitecellars.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Adobe Road Winery',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'https://www.adoberoadwines.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Azari',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'https://www.azarivineyards.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Cline Cellars',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'http://clinecellars.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Clouds Rest',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'https://www.cloudsrest.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'DeLouch Vineyards',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'https://deloachvineyards.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Enriquez Wines',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'https://enriquezwines.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Fogline Vineyards',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'https://foglinevineyards.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Jackson Family Wines',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'http://jacksonfamilywines.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Karah Estate Vineyard',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'https://www.karahestatevineyard.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Keller Estate',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'http://www.kellerestate.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Macphail Wines',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'http://www.macphailwine.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'McEvoy Ranch',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'https://www.mcevoyranch.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Pax',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'https://paxwine.com/about',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Pellet Estate',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'http://www.pelletestate.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Ramey Wine Cellars',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'http://www.rameywine.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Rodney Strong',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'http://www.rodneystrong.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Sojourn Cellars',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'http://www.sojourncellars.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Sonoma Portworks',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'http://portworks.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Three Sticks',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'http://www.threestickswines.com/',
    type: 'Vineyard & Winery',
  },
  {
    name: 'Trombetta Family Wines',
    img: {
      url: 'http://via.placeholder.com/619x437',
      altText: 'Placeholder Alt Text',
    },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra ligula vitae ligula hendrerit sodales sit amet eget neque. Integer porta, tortor facilisis volutpat blandit, neque felis pretium ligula, ultricies dignissim risus nulla sed metus. Cras eu pharetra est.',
    varitelas: ['Pinot Noir', 'Chardonnay'],
    website: 'https://www.trombettawines.com/',
    type: 'Vineyard & Winery',
  },
]

export default wineries
